apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-chat

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: redhat-chat
  tech-preview: "true"

images:
  - name: quay.io/maximilianopizarro/redhat-chat
    newTag: latest

