apiVersion: v1
kind: ServiceAccount
metadata:
  name: redhat-chat
  labels:
    app: redhat-chat
    tech-preview: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  labels:
    app: mongodb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meilisearch
  labels:
    app: meilisearch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vectordb
  labels:
    app: vectordb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-api
  labels:
    app: rag-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  labels:
    app: pipeline

